apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-onepage
  labels:
    app: cv-onepage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cv-onepage
  template:
    metadata:
      labels:
        app: cv-onepage
    spec:
      containers:
        - name: cv-onepage
          image: oumaymazekri/cv-test:latest
          ports:
            - containerPort: 81
---
apiVersion: v1
kind: Service
metadata:
  name: cv-onepage-service
spec:
  type: NodePort
  selector:
    app: cv-onepage
  ports:
    - port: 80        # port interne du service
      targetPort: 81  # port du container
      nodePort: 30085 # port expos√© sur la VM
