- name: Download Terraform
  get_url:
    url: https://releases.hashicorp.com/terraform/1.7.7/terraform_1.7.7_linux_amd64.zip
    dest: /tmp/terraform.zip

- name: Unzip Terraform
  unarchive:
    src: /tmp/terraform.zip
    dest: /usr/local/bin/
    remote_src: yes

- name: Verify Terraform
  command: terraform -version
